_index:
    pattern:  /
    defaults: { _controller: "FastSisdikBundle:Default:index" }

# third party bundles ---------------------------------------------------------------------------------------- #

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb


# end of third party bundle ---------------------------------------------------------------------------------- #


_settings:
    resource: "@FastSisdikBundle/Controller/SettingsController.php"
    type:     annotation
    prefix:   /settings

settings_user:
    resource: "@FastSisdikBundle/Controller/SettingsUserController.php"
    type:     annotation
    prefix:   /settings

settings_school:
    resource: "@FastSisdikBundle/Controller/SettingsSchoolController.php"
    type:     annotation
    prefix:   /settings

settings_specsch:
    resource: "@FastSisdikBundle/Controller/SekolahController.php"
    type:     annotation
    prefix:   /settings

settings_placement:
    resource: "@FastSisdikBundle/Controller/PenjurusanController.php"
    type:     annotation
    prefix:   /settings

settings_year:
    resource: "@FastSisdikBundle/Controller/TahunController.php"
    type:     annotation
    prefix:   /settings

settings_admissiongroup:
    resource: "@FastSisdikBundle/Controller/GelombangController.php"
    type:     annotation
    prefix:   /settings

settings_feetype:
    resource: "@FastSisdikBundle/Controller/JenisbiayaController.php"
    type:     annotation
    prefix:   /

settings_feeonce:
    resource: "@FastSisdikBundle/Controller/BiayaSekaliController.php"
    type:     annotation
    prefix:   /

settings_feerecur:
    resource: "@FastSisdikBundle/Controller/BiayaRutinController.php"
    type:     annotation
    prefix:   /

fee_registration:
    resource: "@FastSisdikBundle/Controller/BiayaPendaftaranController.php"
    type:     annotation
    prefix:   /

student:
    resource: "@FastSisdikBundle/Controller/SiswaController.php"
    type:     annotation
    prefix:   /

student_username:
    resource: "@FastSisdikBundle/Controller/SiswaUsernameController.php"
    type:     annotation
    prefix:   /

class:
    resource: "@FastSisdikBundle/Controller/KelasController.php"
    type:     annotation
    prefix:   /

academicyear:
    resource: "@FastSisdikBundle/Controller/TahunAkademikController.php"
    type:     annotation
    prefix:   /

classguardian:
    resource: "@FastSisdikBundle/Controller/WaliKelasController.php"
    type:     annotation
    prefix:   /

studentclass:
    resource: "@FastSisdikBundle/Controller/SiswaKelasController.php"
    type:     annotation
    prefix:   /

smstemplate:
    resource: "@FastSisdikBundle/Controller/TemplatesmsController.php"
    type:     annotation
    prefix:   /

academiccalendar:
    resource: "@FastSisdikBundle/Controller/KalenderPendidikanController.php"
    type:     annotation
    prefix:   /

presence_status:
    resource: "@FastSisdikBundle/Controller/StatusKehadiranKepulanganController.php"
    type:     annotation
    prefix:   /

presence_schedule_single:
    resource: "@FastSisdikBundle/Controller/JadwalKehadiranKepulanganSingleController.php"
    type:     annotation
    prefix:   /

presence_schedule:
    resource: "@FastSisdikBundle/Controller/JadwalKehadiranKepulanganController.php"
    type:     annotation
    prefix:   /

tingkatkelas:
    resource: "@FastSisdikBundle/Controller/TingkatController.php"
    type:     annotation
    prefix:   /

attendance_machine:
    resource: "@FastSisdikBundle/Controller/MesinKehadiranController.php"
    type:     annotation
    prefix:   /

studentspresence:
    resource: "@FastSisdikBundle/Controller/KehadiranSiswaController.php"
    type:     annotation
    prefix:   /

studentspresence_localapi:
    resource: "@FastSisdikBundle/Controller/KehadiranSiswaLocalAPIController.php"
    type:     annotation
    prefix:   /

rewardtype:
    resource: "@FastSisdikBundle/Controller/JenisImbalanController.php"
    type:     annotation
    prefix:   /

rewardamount:
    resource: "@FastSisdikBundle/Controller/ImbalanPendaftaranController.php"
    type:     annotation
    prefix:   /

regcommittee:
    resource: "@FastSisdikBundle/Controller/PanitiaPendaftaranController.php"
    type:     annotation
    prefix:   /

applicant:
    resource: "@FastSisdikBundle/Controller/SiswaApplicantController.php"
    type:     annotation
    prefix:   /

payment:
    resource: "@FastSisdikBundle/Controller/SiswaApplicantPaymentController.php"
    type:     annotation
    prefix:   /

payment_oncefee:
    resource: "@FastSisdikBundle/Controller/PembayaranSekaliController.php"
    type:     annotation
    prefix:   /

payment_registrationfee:
    resource: "@FastSisdikBundle/Controller/PembayaranPendaftaranController.php"
    type:     annotation
    prefix:   /

payment_registrationfee_print:
    resource: "@FastSisdikBundle/Controller/PembayaranPendaftaranCetakController.php"
    type:     annotation
    prefix:   /

printreceiptsoption:
    resource: "@FastSisdikBundle/Controller/PilihanCetakKwitansiController.php"
    type:     annotation
    prefix:   /

ortuwali:
    resource: "@FastSisdikBundle/Controller/OrangtuaWaliController.php"
    type:     annotation
    prefix:   /

layanansms:
    resource: "@FastSisdikBundle/Controller/PilihanLayananSmsController.php"
    type:     annotation
    prefix:   /

smspendaftaran:
    resource: "@FastSisdikBundle/Controller/LayananSmsPendaftaranController.php"
    type:     annotation
    prefix:   /

riwayatpenyakit:
    resource: "@FastSisdikBundle/Controller/PenyakitSiswaController.php"
    type:     annotation
    prefix:   /

pendidikansiswa:
    resource: "@FastSisdikBundle/Controller/PendidikanSiswaController.php"
    type:     annotation
    prefix:   /

jenisdokumensiswa:
    resource: "@FastSisdikBundle/Controller/JenisDokumenSiswaController.php"
    type:     annotation
    prefix:   /

dokumensiswa:
    resource: "@FastSisdikBundle/Controller/DokumenSiswaController.php"
    type:     annotation
    prefix:   /

referensi:
    resource: "@FastSisdikBundle/Controller/ReferensiController.php"
    type:     annotation
    prefix:   /

sekolahasal:
    resource: "@FastSisdikBundle/Controller/SekolahAsalController.php"
    type:     annotation
    prefix:   /

laporanpendaftaran:
    resource: "@FastSisdikBundle/Controller/SiswaApplicantReportController.php"
    type:     annotation
    prefix:   /

tahkik:
    resource: "@FastSisdikBundle/Controller/SiswaTahkikController.php"
    type:     annotation
    prefix:   /


# local APIs ---------------------------------------------------------------------------------- #
localapi_logsmskeluar:
    resource: "@FastSisdikBundle/Controller/LocalAPILogsmsKeluarController.php"
    type:     annotation
    prefix:   /


# end of local APIs ---------------------------------------------------------------------------------- #


# redirect all non-existent route
anything:
    path:     /{path}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true
    requirements:
        path: ".+"