services:
    fast_sisdik.menu_builder:
        class: Fast\SisdikBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]

    fast_sisdik.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: fast_sisdik.menu_builder
        factory_method: createMainMenu
        arguments: ["@request", "@service_container"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    fast_sisdik.registration.form.type:
        class: Fast\SisdikBundle\Form\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: fast_sisdikbundle_registration }

    fast_sisdik.profile.form.type:
        class: Fast\SisdikBundle\Form\ProfileFormType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: fast_sisdikbundle_profile }

    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    fast.twig.fast_extension:
        class: Fast\SisdikBundle\Twig\FastExtension
        tags:
            - { name: twig.extension }

    sisdik.messenger:
        class:        Fast\SisdikBundle\Util\Messenger
        scope:        prototype
        arguments:    ["@doctrine.orm.entity_manager", "@router", "%messenger_provider%", "%messenger_scheme%", "%messenger_host%", "%messenger_port%", "%messenger_user%", "%messenger_password%", "%messenger_resource%", "%messenger_apikey%", "%messenger_report%"]

    sisdik.translator.form.extractor:
        class: Fast\SisdikBundle\Translator\FormExtractor
        tags:
            - { name: jms_translation.file_visitor }
        arguments: ["@jms_translation.doc_parser"]

    sisdik.translator.entity.extractor:
        class: Fast\SisdikBundle\Translator\EntityExtractor
        tags:
            - { name: jms_translation.file_visitor }
