parameters:
#    fast_sisdik.example.class: Fast\SisdikBundle\Example

services:
    fast_sisdik.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { rightmenu: "@fast_sisdik.menu.main=" }
            - {}
            - { title: "%app_title%", titleRoute: "_index", fixedTop: true, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    fast_sisdik.menu_builder:
        class: Fast\SisdikBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]

    fast_sisdik.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: fast_sisdik.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: mainmenu } # The alias is what is used to retrieve the menu

#     fast.sisdik.menu.voter.request:
#         class: Fast\SisdikBundle\Menu\RouteVoter
#         arguments:
#             - "@service_container"
#         tags:
#             - { name: knp_menu.voter }

    fast_sisdik.registration.form.type:
        class: Fast\SisdikBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fast_sisdikbundle_registration }

    fast_sisdik.profile.form.type:
        class: Fast\SisdikBundle\Form\ProfileFormType
        arguments: ["@service_container", %fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fast_sisdikbundle_profile }

#    fast_sisdik.setting.user.form.type:
#        class: Fast\SisdikBundle\Form\UserFormType
#        arguments: ["@service_container"]
#        tags:
#            - { name: form.type, alias: fast_setting_user }
#
#    fast_sisdik.setting.user.register.form.type:
#        class: Fast\SisdikBundle\Form\UserRegisterFormType
#        arguments: ["@service_container"]
#        tags:
#            - { name: form.type, alias: fast_setting_user_register }

    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }

    fast.twig.fast_extension:
        class: Fast\SisdikBundle\Twig\FastExtension
        tags:
            - { name: twig.extension }

    fast_sisdik.messenger:
        class:        Fast\SisdikBundle\Util\Messenger
        scope:        prototype
        arguments:    ["@service_container", "%messenger_provider%", "%messenger_scheme%", "%messenger_host%", "%messenger_port%", "%messenger_user%", "%messenger_password%", "%messenger_resource%", "%messenger_apikey%", "%messenger_report%"]

