parameters:
#    fast_sisdik.example.class: Fast\SisdikBundle\Example

services:
    fast_sisdik.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { rightmenu: "@fast_sisdik.menu.main=" }
            - {}
            - { title: "%app_title%", titleRoute: "_index", fixedTop: true, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }
            
    fast_sisdik.menu_builder:
        class: Fast\SisdikBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]

    fast_sisdik.menu.main:
        # the service definition requires setting the class
        class: Knp\Menu\MenuItem
        factory_service: fast_sisdik.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        # needed as we have the request as a dependency here
        scope: request
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu, alias: mainmenu }

    fast.sisdik.menu.voter.request:
        class: Fast\SisdikBundle\Menu\RouteVoter
        arguments:
            - "@service_container"
        tags:
            - { name: knp_menu.voter }

    fast_user.registration.form.type:
        class: Fast\SisdikBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fast_user_registration }

    fast_user.profile.form.type:
        class: Fast\SisdikBundle\Form\ProfileFormType
        arguments: ["@service_container", %fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fast_user_profile }

    fast_setting.user.form.type:
        class: Fast\SisdikBundle\Form\UserFormType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: fast_setting_user }

    fast_setting.user.register.form.type:
        class: Fast\SisdikBundle\Form\UserRegisterFormType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: fast_setting_user_register }

    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }

