imports:
    - { resource: config.yml }

doctrine:
   orm:
       metadata_cache_driver: apc
       result_cache_driver: apc
       query_cache_driver: apc

monolog:
    channels: ["messenger"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
        messenger:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%_messenger.log"
            channels:     [messenger]

framework:
    templating:
        engines: ['twig']
        assets_base_urls:
            http: ["%assets_base_url_http%"]
            ssl: []
