security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_PENGAWAS: [ROLE_USER]
        ROLE_PEMBINA: [ROLE_USER]
        ROLE_SISWA: [ROLE_USER]
        ROLE_PANITIA_PSB: [ROLE_USER]
        ROLE_KETUA_PANITIA_PSB: [ROLE_PANITIA_PSB, ROLE_USER]
        ROLE_KASIR: [ROLE_USER]
        ROLE_BENDAHARA: [ROLE_KASIR, ROLE_USER]
        ROLE_GURU_PIKET: [ROLE_USER]
        ROLE_GURU: [ROLE_GURU_PIKET, ROLE_USER]
        ROLE_WALI_KELAS: [ROLE_GURU, ROLE_SISWA, ROLE_USER]
        ROLE_WAKIL_KEPALA_SEKOLAH: [ROLE_GURU, ROLE_USER]
        ROLE_KEPALA_SEKOLAH: [ROLE_WAKIL_KEPALA_SEKOLAH, ROLE_GURU, ROLE_USER]
        ROLE_ADMIN: [ROLE_KEPALA_SEKOLAH, ROLE_WAKIL_KEPALA_SEKOLAH, ROLE_GURU_PIKET, ROLE_PANITIA_PSB, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_SISWA, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main_firewall:
            pattern: ^/
            security: true
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: false
#            remember_me:
#                key: %secret%
#                lifetime: 3600
#                path: /
#                domain: ~
            anonymous: true
            logout: true
            switch_user: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        - { path: ^/(_(profiler|wdt)|css|images|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_local, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/_local, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 192.168.1.11 }
        - { path: ^/_api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }




