BiayaRutin:
  type: entity
  table: biaya_rutin
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nominal:
      type: bigint
      nullable: true
    perulangan:
      type: string
      length: null
      fixed: false
      nullable: true
    urutan:
      type: smallint
      nullable: true
  manyToOne:
    gelombang:
      targetEntity: Gelombang
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        gelombang_id:
          referencedColumnName: id
      orphanRemoval: false
    tahunmasuk:
      targetEntity: Tahunmasuk
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tahunmasuk_id:
          referencedColumnName: id
      orphanRemoval: false
    jenisbiaya:
      targetEntity: Jenisbiaya
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        jenisbiaya_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
