CalonPembayaranRutin:
  type: entity
  table: calon_pembayaran_rutin
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: IDENTITY
    nominalPembayaran:
      type: bigint
      nullable: true
      column: nominal_pembayaran
    keterangan:
      type: string
      length: 300
      fixed: false
      nullable: true
    waktuSimpan:
      type: datetime
      nullable: true
      column: waktu_simpan
    waktuUbah:
      type: datetime
      nullable: false
      column: waktu_ubah
  manyToOne:
    biayaRutin:
      targetEntity: BiayaRutin
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        biaya_rutin_id:
          referencedColumnName: id
      orphanRemoval: false
    calonSiswa:
      targetEntity: CalonSiswa
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        calon_siswa_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
