CalonSiswa:
    type: entity
    table: calon_siswa
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nomorPendaftaran:
            type: smallint
            nullable: true
            column: nomor_pendaftaran
        namaLengkap:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: nama_lengkap
        jenisKelamin:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: jenis_kelamin
        fotoPendaftaran:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: foto_pendaftaran
        foto:
            type: string
            length: 100
            fixed: false
            nullable: true
        agama:
            type: string
            length: 100
            fixed: false
            nullable: true
        tempatLahir:
            type: string
            length: 400
            fixed: false
            nullable: true
            column: tempat_lahir
        tanggalLahir:
            type: date
            nullable: true
            column: tanggal_lahir
        email:
            type: string
            length: 100
            fixed: false
            nullable: true
        namaPanggilan:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: nama_panggilan
        kewarganegaraan:
            type: string
            length: 200
            fixed: false
            nullable: true
        anakKe:
            type: smallint
            nullable: true
            column: anak_ke
        jumlahSaudarakandung:
            type: smallint
            nullable: true
            column: jumlah_saudarakandung
        jumlahSaudaratiri:
            type: smallint
            nullable: true
            column: jumlah_saudaratiri
        statusOrphan:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: status_orphan
        bahasaSeharihari:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: bahasa_seharihari
        alamat:
            type: string
            length: 500
            fixed: false
            nullable: true
        kodepos:
            type: string
            length: 30
            fixed: false
            nullable: true
        telepon:
            type: string
            length: 100
            fixed: false
            nullable: true
        ponselSiswa:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: ponsel_siswa
        ponselOrangtuawali:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: ponsel_orangtuawali
        sekolahTinggaldi:
            type: string
            length: 400
            fixed: false
            nullable: true
            column: sekolah_tinggaldi
        jarakTempat:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: jarak_tempat
        caraKesekolah:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: cara_kesekolah
        beratbadan:
            type: smallint
            nullable: true
        tinggibadan:
            type: smallint
            nullable: true
        golongandarah:
            type: string
            length: 50
            fixed: false
            nullable: true
        waktuSimpan:
            type: datetime
            nullable: true
            column: waktu_simpan
        waktuUbah:
            type: datetime
            nullable: false
            column: waktu_ubah
    manyToOne:
        dibuatOleh:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                dibuat_oleh_id:
                    referencedColumnName: id
            orphanRemoval: false
        sekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sekolah_id:
                    referencedColumnName: id
            orphanRemoval: false
        tahunmasuk:
            targetEntity: Tahunmasuk
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tahunmasuk_id:
                    referencedColumnName: id
            orphanRemoval: false
        gelombang:
            targetEntity: Gelombang
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                gelombang_id:
                    referencedColumnName: id
            orphanRemoval: false
        diubahOleh:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                diubah_oleh_id:
                    referencedColumnName: id
            orphanRemoval: false
        referensi:
            targetEntity: Referensi
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                referensi_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
