FosUser:
    type: entity
    table: fos_user
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 255
            fixed: false
            nullable: false
        usernameCanonical:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: username_canonical
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        emailCanonical:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            length: 255
            fixed: false
            nullable: false
        password:
            type: string
            length: 255
            fixed: false
            nullable: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
    manyToOne:
        idguru:
            targetEntity: Guru
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idguru:
                    referencedColumnName: id
            orphanRemoval: false
        idsekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idsekolah:
                    referencedColumnName: id
            orphanRemoval: false
        idsiswa:
            targetEntity: Siswa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idsiswa:
                    referencedColumnName: id
            orphanRemoval: false
        idstaf:
            targetEntity: Staf
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idstaf:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
