Guru:
  type: entity
  table: guru
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nama:
      type: string
      length: 400
      fixed: false
      nullable: true
    jenisKelamin:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: jenis_kelamin
    foto:
      type: string
      length: 400
      fixed: false
      nullable: true
    agama:
      type: integer
      unsigned: false
      nullable: true
    tempatLahir:
      type: string
      length: 400
      fixed: false
      nullable: true
      column: tempat_lahir
    tanggalLahir:
      type: date
      nullable: true
      column: tanggal_lahir
    alamat:
      type: string
      length: 500
      fixed: false
      nullable: true
    telepon:
      type: string
      length: 100
      fixed: false
      nullable: true
    email:
      type: string
      length: 100
      fixed: false
      nullable: true
    nomorInduk:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: nomor_induk
    username:
      type: string
      length: 255
      fixed: false
      nullable: true
    status:
      type: boolean
      nullable: true
  manyToOne:
    sekolah:
      targetEntity: Sekolah
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        sekolah_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
