GuruMp:
  type: entity
  table: guru_mp
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  manyToOne:
    guru:
      targetEntity: Guru
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        guru_id:
          referencedColumnName: id
      orphanRemoval: false
    mataPelajaran:
      targetEntity: MataPelajaran
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        mata_pelajaran_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
