ImbalanPendaftaran:
  type: entity
  table: imbalan_pendaftaran
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nominal:
      type: integer
      unsigned: false
      nullable: false
  manyToOne:
    jenisImbalan:
      targetEntity: JenisImbalan
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        jenis_imbalan_id:
          referencedColumnName: id
      orphanRemoval: false
    gelombang:
      targetEntity: Gelombang
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        gelombang_id:
          referencedColumnName: id
      orphanRemoval: false
    tahunmasuk:
      targetEntity: Tahunmasuk
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tahunmasuk_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
