JadwalNonkbm:
    type: entity
    table: jadwal_nonkbm
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        dari:
            type: date
            nullable: true
        hingga:
            type: date
            nullable: true
        keterangan:
            type: string
            length: 500
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
