JadwalCmp:
    type: entity
    table: jadwal_cmp
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        tanggal:
            type: datetime
            nullable: true
        jam:
            type: string
            length: 100
            fixed: false
            nullable: true
        keterangan:
            type: string
            length: 500
            fixed: false
            nullable: true
    manyToOne:
        guru:
            targetEntity: Guru
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                guru_id:
                    referencedColumnName: id
            orphanRemoval: false
        cukilMp:
            targetEntity: CukilMp
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cukil_mp_id:
                    referencedColumnName: id
            orphanRemoval: false
        kelas:
            targetEntity: Kelas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                kelas_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
