JadwalBel:
  type: entity
  table: jadwal_bel
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    hari:
      type: integer
      unsigned: false
      nullable: true
    dariJam:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: dari_jam
    hinggaJam:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: hingga_jam
    berulang:
      type: boolean
      nullable: true
    file:
      type: string
      length: 100
      fixed: false
      nullable: true
    aktif:
      type: boolean
      nullable: true
  manyToOne:
    tahun:
      targetEntity: Tahun
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tahun_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
