JadwalSms:
    type: entity
    table: jadwal_sms
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        perulangan:
            type: string
            length: null
            fixed: false
            nullable: true
        mingguanHariKe:
            type: boolean
            nullable: true
            column: mingguan_hari_ke
        bulananHariKe:
            type: boolean
            nullable: true
            column: bulanan_hari_ke
        dariJam:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: dari_jam
        hinggaJam:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: hingga_jam
        kategori:
            type: boolean
            nullable: true
        urutanPeriksa:
            type: smallint
            nullable: true
            column: urutan_periksa
    manyToOne:
        idtahun:
            targetEntity: Tahun
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtahun:
                    referencedColumnName: id
            orphanRemoval: false
        idkelas:
            targetEntity: Kelas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idkelas:
                    referencedColumnName: id
            orphanRemoval: false
        idtemplatesms:
            targetEntity: Templatesms
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtemplatesms:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
