KalenderPendidikan:
    type: entity
    table: kalender_pendidikan
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        tanggal:
            type: date
            nullable: true
        keterangan:
            type: string
            length: 500
            fixed: false
            nullable: true
        kbm:
            type: boolean
            nullable: false
    manyToOne:
        idsekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idsekolah:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
