KelompokMp:
    type: entity
    table: kelompok_mp
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nama:
            type: string
            length: 400
            fixed: false
            nullable: true
        urutan:
            type: integer
            unsigned: false
            nullable: true
    manyToOne:
        sekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sekolah_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
