LogsmsKeluar:
    type: entity
    table: logsms_keluar
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        ke:
            type: string
            length: 50
            fixed: false
            nullable: true
        teks:
            type: string
            length: 500
            fixed: false
            nullable: true
        dlr:
            type: boolean
            nullable: true
        dlrtime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
