MataPelajaran:
    type: entity
    table: mata_pelajaran
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nama:
            type: string
            length: 400
            fixed: false
            nullable: true
        kode:
            type: string
            length: 50
            fixed: false
            nullable: true
        penanggungJawab:
            type: string
            length: 400
            fixed: false
            nullable: true
            column: penanggung_jawab
        jumlahJam:
            type: integer
            unsigned: false
            nullable: true
            column: jumlah_jam
        standarKompetensi:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: standar_kompetensi
    manyToOne:
        kelompokMp:
            targetEntity: KelompokMp
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                kelompok_mp_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
