MesinKehadiran:
    type: entity
    table: mesin_kehadiran
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        alamatIp:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: alamat_ip
        commkey:
            type: string
            length: 45
            fixed: false
            nullable: false
        aktif:
            type: boolean
            nullable: false
    manyToOne:
        sekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sekolah_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
