NilaiPs:
    type: entity
    table: nilai_ps
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        nominal:
            type: bigint
            nullable: true
        keterangan:
            type: string
            length: 500
            fixed: false
            nullable: true
        waktuCatat:
            type: datetime
            nullable: true
            column: waktu_catat
        waktuUbah:
            type: datetime
            nullable: true
            column: waktu_ubah
    manyToOne:
        idpembayaranSekali:
            targetEntity: PembayaranSekali
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idpembayaran_sekali:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
