PendidikanSiswa:
    type: entity
    table: pendidikan_siswa
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        jenjang:
            type: integer
            unsigned: false
            nullable: true
        nama:
            type: string
            length: 400
            fixed: false
            nullable: true
        alamat:
            type: string
            length: 500
            fixed: false
            nullable: true
        ijazah:
            type: string
            length: 400
            fixed: false
            nullable: true
        ijazahFile:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: ijazah_file
        tahunmasuk:
            type: date
            nullable: true
        tahunkeluar:
            type: date
            nullable: true
        sttbTanggal:
            type: date
            nullable: true
            column: sttb_tanggal
        sttbNo:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: sttb_no
        sttbFile:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: sttb_file
        keterangan:
            type: string
            length: 500
            fixed: false
            nullable: true
    manyToOne:
        referensi:
            targetEntity: Referensi
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                referensi_id:
                    referencedColumnName: id
            orphanRemoval: false
        siswa:
            targetEntity: Siswa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                siswa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
