PenyakitSiswa:
  type: entity
  table: penyakit_siswa
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nama:
      type: string
      length: 400
      fixed: false
      nullable: true
    kelas:
      type: string
      length: 200
      fixed: false
      nullable: true
    tahun:
      type: string
      length: 100
      fixed: false
      nullable: true
    lamasakit:
      type: string
      length: 200
      fixed: false
      nullable: true
    keterangan:
      type: string
      length: 500
      fixed: false
      nullable: true
  manyToOne:
    siswa:
      targetEntity: Siswa
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        siswa_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
