PilihanCetakKwitansi:
    type: entity
    table: pilihan_cetak_kwitansi
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        output:
            type: string
            length: 45
            fixed: false
            nullable: false
    manyToOne:
        sekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sekolah_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
