SiswaKelas:
    type: entity
    table: siswa_kelas
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        aktif:
            type: boolean
            nullable: false
        keterangan:
            type: string
            length: 400
            fixed: false
            nullable: true
    manyToOne:
        kelas:
            targetEntity: Kelas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                kelas_id:
                    referencedColumnName: id
            orphanRemoval: false
        penjurusan:
            targetEntity: Penjurusan
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                penjurusan_id:
                    referencedColumnName: id
            orphanRemoval: false
        siswa:
            targetEntity: Siswa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                siswa_id:
                    referencedColumnName: id
            orphanRemoval: false
        tahun:
            targetEntity: Tahun
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tahun_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
