Siswahadir:
    type: entity
    table: siswahadir
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        tanggal:
            type: date
            nullable: true
        hadir:
            type: boolean
            nullable: true
        telatDlr:
            type: integer
            unsigned: false
            nullable: true
            column: telat_dlr
        telatDlrtime:
            type: datetime
            nullable: true
            column: telat_dlrtime
        absenDlr:
            type: integer
            unsigned: false
            nullable: true
            column: absen_dlr
        absenDlrtime:
            type: datetime
            nullable: true
            column: absen_dlrtime
    lifecycleCallbacks: {  }
