SiswahadirJcmp:
    type: entity
    table: siswahadir_jcmp
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        hadir:
            type: boolean
            nullable: true
        jamMasuk:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: jam_masuk
        jamKeluar:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: jam_keluar
        keterangan:
            type: string
            length: 500
            fixed: false
            nullable: true
    manyToOne:
        idjadwalCmp:
            targetEntity: JadwalCmp
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idjadwal_cmp:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
