Staf:
    type: entity
    table: staf
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        namaLengkap:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: nama_lengkap
        username:
            type: string
            length: 255
            fixed: false
            nullable: true
    manyToOne:
        idsekolah:
            targetEntity: Sekolah
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idsekolah:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
