Tahunmasuk:
  type: entity
  table: tahunmasuk
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    tahun:
      type: date
      nullable: false
  manyToOne:
    sekolah:
      targetEntity: Sekolah
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        sekolah_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
