TransaksiPembayaranRutin:
    type: entity
    table: transaksi_pembayaran_rutin
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nominalPembayaran:
            type: bigint
            nullable: true
            column: nominal_pembayaran
        keterangan:
            type: string
            length: 300
            fixed: false
            nullable: true
        nomorTransaksi:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: nomor_transaksi
        waktuSimpan:
            type: datetime
            nullable: true
            column: waktu_simpan
    manyToOne:
        pembayaranRutin:
            targetEntity: PembayaranRutin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pembayaran_rutin_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
