WaliKelas:
  type: entity
  table: wali_kelas
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nama:
      type: string
      length: 45
      fixed: false
      nullable: true
  manyToOne:
    kelas:
      targetEntity: Kelas
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        kelas_id:
          referencedColumnName: id
      orphanRemoval: false
    tahun:
      targetEntity: Tahun
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tahun_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
