_index:
    pattern:  /
    defaults: { _controller: "LanggasSisdikBundle:Default:index" }

# third party bundles ---------------------------------------------------------------------------------------- #
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb
# end of third party bundle ---------------------------------------------------------------------------------- #

core_controller:
    resource: "@LanggasSisdikBundle/Controller"
    type:     annotation
    prefix:   /

siswa_controller:
    resource: "@LanggasSisdikBundle/Controller/Siswa"
    type:     annotation
    prefix:   /siswa/

# local APIs ---------------------------------------------------------------------------------- #
localapi_logsmskeluar:
    resource: "@LanggasSisdikBundle/Controller/LocalAPILogsmsKeluarController.php"
    type:     annotation
    prefix:   /
# end of local APIs ---------------------------------------------------------------------------------- #


# public API (REST) ---------------------------------------------------------------------------------- #
#rest:
#    type: rest
#    resource: "routing_rest.yml"
#    prefix: /_api
# end of public APIs ---------------------------------------------------------------------------------- #


# redirect all non-existent route
anything:
    path:     /{path}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true
    requirements:
        path: ".+"
