_index:
    pattern:  /
    defaults: { _controller: "LanggasSisdikBundle:Default:index" }

# third party bundles ---------------------------------------------------------------------------------------- #

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb


# end of third party bundle ---------------------------------------------------------------------------------- #


_settings:
    resource: "@LanggasSisdikBundle/Controller/SettingsController.php"
    type:     annotation
    prefix:   /settings

settings_user:
    resource: "@LanggasSisdikBundle/Controller/SettingsUserController.php"
    type:     annotation
    prefix:   /settings

settings_school:
    resource: "@LanggasSisdikBundle/Controller/SettingsSchoolController.php"
    type:     annotation
    prefix:   /settings

settings_specsch:
    resource: "@LanggasSisdikBundle/Controller/SekolahController.php"
    type:     annotation
    prefix:   /settings

settings_placement:
    resource: "@LanggasSisdikBundle/Controller/PenjurusanController.php"
    type:     annotation
    prefix:   /settings

settings_year:
    resource: "@LanggasSisdikBundle/Controller/TahunController.php"
    type:     annotation
    prefix:   /settings

settings_admissiongroup:
    resource: "@LanggasSisdikBundle/Controller/GelombangController.php"
    type:     annotation
    prefix:   /settings

settings_feetype:
    resource: "@LanggasSisdikBundle/Controller/JenisbiayaController.php"
    type:     annotation
    prefix:   /

settings_feeonce:
    resource: "@LanggasSisdikBundle/Controller/BiayaSekaliController.php"
    type:     annotation
    prefix:   /

settings_feerecur:
    resource: "@LanggasSisdikBundle/Controller/BiayaRutinController.php"
    type:     annotation
    prefix:   /

fee_registration:
    resource: "@LanggasSisdikBundle/Controller/BiayaPendaftaranController.php"
    type:     annotation
    prefix:   /

student:
    resource: "@LanggasSisdikBundle/Controller/SiswaController.php"
    type:     annotation
    prefix:   /

student_username:
    resource: "@LanggasSisdikBundle/Controller/SiswaUsernameController.php"
    type:     annotation
    prefix:   /

class:
    resource: "@LanggasSisdikBundle/Controller/KelasController.php"
    type:     annotation
    prefix:   /

academicyear:
    resource: "@LanggasSisdikBundle/Controller/TahunAkademikController.php"
    type:     annotation
    prefix:   /

classguardian:
    resource: "@LanggasSisdikBundle/Controller/WaliKelasController.php"
    type:     annotation
    prefix:   /

studentclass:
    resource: "@LanggasSisdikBundle/Controller/SiswaKelasController.php"
    type:     annotation
    prefix:   /

smstemplate:
    resource: "@LanggasSisdikBundle/Controller/TemplatesmsController.php"
    type:     annotation
    prefix:   /

academiccalendar:
    resource: "@LanggasSisdikBundle/Controller/KalenderPendidikanController.php"
    type:     annotation
    prefix:   /

jadwal_kehadiran:
    resource: "@LanggasSisdikBundle/Controller/JadwalKehadiranController.php"
    type:     annotation
    prefix:   /

tingkatkelas:
    resource: "@LanggasSisdikBundle/Controller/TingkatController.php"
    type:     annotation
    prefix:   /

attendance_machine:
    resource: "@LanggasSisdikBundle/Controller/MesinKehadiranController.php"
    type:     annotation
    prefix:   /

kehadiran_siswa:
    resource: "@LanggasSisdikBundle/Controller/KehadiranSiswaController.php"
    type:     annotation
    prefix:   /

kehadiran_siswa_laporan:
    resource: "@LanggasSisdikBundle/Controller/KehadiranSiswaReportController.php"
    type:     annotation
    prefix:   /

kehadiran_siswa_localapi:
    resource: "@LanggasSisdikBundle/Controller/KehadiranSiswaLocalAPIController.php"
    type:     annotation
    prefix:   /

rewardtype:
    resource: "@LanggasSisdikBundle/Controller/JenisImbalanController.php"
    type:     annotation
    prefix:   /

rewardamount:
    resource: "@LanggasSisdikBundle/Controller/ImbalanPendaftaranController.php"
    type:     annotation
    prefix:   /

regcommittee:
    resource: "@LanggasSisdikBundle/Controller/PanitiaPendaftaranController.php"
    type:     annotation
    prefix:   /

applicant:
    resource: "@LanggasSisdikBundle/Controller/SiswaApplicantController.php"
    type:     annotation
    prefix:   /

payment:
    resource: "@LanggasSisdikBundle/Controller/SiswaApplicantPaymentController.php"
    type:     annotation
    prefix:   /

payment_oncefee:
    resource: "@LanggasSisdikBundle/Controller/PembayaranSekaliController.php"
    type:     annotation
    prefix:   /

payment_registrationfee:
    resource: "@LanggasSisdikBundle/Controller/PembayaranPendaftaranController.php"
    type:     annotation
    prefix:   /

payment_registrationfee_print:
    resource: "@LanggasSisdikBundle/Controller/PembayaranPendaftaranCetakController.php"
    type:     annotation
    prefix:   /

printreceiptsoption:
    resource: "@LanggasSisdikBundle/Controller/PilihanCetakKwitansiController.php"
    type:     annotation
    prefix:   /

ortuwali:
    resource: "@LanggasSisdikBundle/Controller/OrangtuaWaliController.php"
    type:     annotation
    prefix:   /

layanansms:
    resource: "@LanggasSisdikBundle/Controller/PilihanLayananSmsController.php"
    type:     annotation
    prefix:   /

smspendaftaran:
    resource: "@LanggasSisdikBundle/Controller/LayananSmsPendaftaranController.php"
    type:     annotation
    prefix:   /

riwayatpenyakit:
    resource: "@LanggasSisdikBundle/Controller/PenyakitSiswaController.php"
    type:     annotation
    prefix:   /

pendidikansiswa:
    resource: "@LanggasSisdikBundle/Controller/PendidikanSiswaController.php"
    type:     annotation
    prefix:   /

jenisdokumensiswa:
    resource: "@LanggasSisdikBundle/Controller/JenisDokumenSiswaController.php"
    type:     annotation
    prefix:   /

dokumensiswa:
    resource: "@LanggasSisdikBundle/Controller/DokumenSiswaController.php"
    type:     annotation
    prefix:   /

referensi:
    resource: "@LanggasSisdikBundle/Controller/ReferensiController.php"
    type:     annotation
    prefix:   /

sekolahasal:
    resource: "@LanggasSisdikBundle/Controller/SekolahAsalController.php"
    type:     annotation
    prefix:   /

laporanpendaftaran:
    resource: "@LanggasSisdikBundle/Controller/SiswaApplicantReportController.php"
    type:     annotation
    prefix:   /

laporan-pembayaran-pendaftaran:
    resource: "@LanggasSisdikBundle/Controller/SiswaApplicantReportPaymentController.php"
    type:     annotation
    prefix:   /

laporan-transaksi-keuangan:
    resource: "@LanggasSisdikBundle/Controller/LaporanTransaksiKeuanganController.php"
    type:     annotation
    prefix:   /

tahkik:
    resource: "@LanggasSisdikBundle/Controller/SiswaTahkikController.php"
    type:     annotation
    prefix:   /

penempatansiswakelas:
    resource: "@LanggasSisdikBundle/Controller/PenempatanSiswaKelasController.php"
    type:     annotation
    prefix:   /

token_sekolah:
    resource: "@LanggasSisdikBundle/Controller/TokenSekolahController.php"
    type:     annotation
    prefix:   /


# local APIs ---------------------------------------------------------------------------------- #
localapi_logsmskeluar:
    resource: "@LanggasSisdikBundle/Controller/LocalAPILogsmsKeluarController.php"
    type:     annotation
    prefix:   /
# end of local APIs ---------------------------------------------------------------------------------- #


# public API (REST) ---------------------------------------------------------------------------------- #
#rest:
#    type: rest
#    resource: "routing_rest.yml"
#    prefix: /_api
# end of public APIs ---------------------------------------------------------------------------------- #


# redirect all non-existent route
anything:
    path:     /{path}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true
    requirements:
        path: ".+"
