services:
    langgas_sisdik.menu_builder:
        class: Langgas\SisdikBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]

    langgas_sisdik.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: langgas_sisdik.menu_builder
        factory_method: createMainMenu
        arguments: ["@request", "@service_container"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    langgas_sisdik.registration.form.type:
        class: Langgas\SisdikBundle\Form\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: langgas_sisdikbundle_registration }

    langgas_sisdik.profile.form.type:
        class: Langgas\SisdikBundle\Form\ProfileFormType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: langgas_sisdikbundle_profile }

    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    langgas.twig.langgas_extension:
        class: Langgas\SisdikBundle\Twig\LanggasExtension
        tags:
            - { name: twig.extension }

    sisdik.messenger:
        class:        Langgas\SisdikBundle\Util\Messenger
        scope:        prototype
        arguments:    ["@doctrine.orm.entity_manager", "@router", "@monolog.logger.messenger", "%messenger_provider%", "%messenger_scheme%", "%messenger_host%", "%messenger_port%", "%messenger_user%", "%messenger_password%", "%messenger_resource%", "%messenger_apikey%", "%messenger_report%"]

    sisdik.translator.form.extractor:
        class: Langgas\SisdikBundle\Translator\FormExtractor
        tags:
            - { name: jms_translation.file_visitor }
        arguments: ["@jms_translation.doc_parser"]

    sisdik.translator.entity.extractor:
        class: Langgas\SisdikBundle\Translator\EntityExtractor
        tags:
            - { name: jms_translation.file_visitor }
